Server/Cloud/SmoovPOS/merchant/Models/Tax/TaxItemModel.cs
using Com.SmoovPOS.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmoovPOS.UI.Models.Tax
{
    public class TaxItemModel
    {
        public int indexStore { get; set; }
        public string storeName { get; set; }
        public ServiceCharge serviceCharge {get; set;}
        public IEnumerable<TaxItem> listTaxItem { get; set; } 
    }
}

Server/Cloud/SmoovPOS/merchant/Models/Tax/TaxModel.cs
using Com.SmoovPOS.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmoovPOS.UI.Models.Tax
{
    public class TaxModel
    {
        public List<TaxItemModel> listTaxItem{ set; get; }
        public Inventory[] inventoryList { get; set; }
        public string id { get; set; }
        public List<string> listStoreId  { get; set; }
    }
}

Server/Cloud/SmoovPOS/merchant/Controllers/TaxController.cs
using Com.SmoovPOS.Entity;
using Newtonsoft.Json.Linq;
using SmoovPOS.Common;
using SmoovPOS.Common.Controllers;
using SmoovPOS.UI.Models.Tax;
using SmoovPOS.Utility.WSInventoryReference;
using SmoovPOS.Utility.WSMerchantSettingReference;
using SmoovPOS.Utility.WSTaxReference;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SmoovPOS.UI.Controllers
{
    public class TaxController : BaseController
    {
        [Authorize]
        // GET: Tax
        public ActionResult Index()
        {
            //ViewBag.NumberInit = CheckInitiation();
            ViewBag.Class = "tax";
            WSTaxClient client = new WSTaxClient();
            WSInventoryClient clientInventory = new WSInventoryClient();
            TaxModel taxModel = new TaxModel();
            Inventory[] ListInventory = clientInventory.WSGetAll(ConstantSmoovs.CouchBase.DesigndocInventory, ConstantSmoovs.CouchBase.GetAllInventories, VariableConfigController.GetBucket());
            taxModel.inventoryList = ListInventory;
            var listTax = client.GetAllTax(ConstantSmoovs.CouchBase.DesignDocSettingMerchant, ConstantSmoovs.CouchBase.GetAllTax, VariableConfigController.GetBucket());
            List<TaxItemModel> listTaxItem = new List<TaxItemModel>();
            taxModel.listStoreId = new List<string>();
           
            if (listTax == null || listTax.Count() == 0)
            {
                Tax tax = new Tax();
                tax._id = Guid.NewGuid().ToString();
                tax.display = true;
                tax.status = true;
                tax.userID = VariableConfigController.GetUserID();
                tax.userOwner = VariableConfigController.GetBucket();                 
                var onlineInventory = ListInventory.Where(i => i.index == 1).FirstOrDefault();
                ServiceCharge servicecharge = new ServiceCharge();
                servicecharge.index = 1;
                servicecharge.serviceChargeRate = 0.00;
                servicecharge.serviceChargeValue = 0.00;
                servicecharge.store = onlineInventory;
                tax.arrServiceCharge = new List<ServiceCharge>() {servicecharge};
                taxModel.listStoreId.Add(onlineInventory._id);
                int response = client.WSCreateTax(tax, VariableConfigController.GetBucket());
                taxModel.id = tax._id;
            }
            else
            {
                foreach (Inventory inventory in ListInventory)
                {
                    TaxItemModel taxItem = new TaxItemModel();
                    taxItem.indexStore = inventory.index;
                    var serviceCharge = listTax[0].arrServiceCharge.Where(s => s.index == inventory.index).FirstOrDefault();
                    taxItem.serviceCharge = serviceCharge;                  
                    var listTaxValue = listTax[0].arrayTax != null ? listTax[0].arrayTax.Where(t => t.storeInformation.Where(s => s.index == inventory.index).Count() > 0) : new List<TaxItem>() ;
                    taxItem.listTaxItem = listTaxValue;
                    taxItem.storeName = inventory.businessID;
                    listTaxItem.Add(taxItem);
                    if(serviceCharge != null || inventory.index == 1){
                         taxModel.listStoreId.Add(inventory._id);
                    }
                }

                taxModel.id = listTax[0].id;
            }
            taxModel.listTaxItem = listTaxItem;
            client.Close();
            clientInventory.Close();
            return View(taxModel);
        }
        public ActionResult ViewNewTax()
        {
            return PartialView("NewTax");
        }

        [HttpPost]
        public ActionResult NewTax()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {

            string strIdStore = collection["idStore"];
            string strServiceCharge = collection["serviceCharge"];
            string taxId = collection["taxId"];

            if (!string.IsNullOrWhiteSpace(collection["serviceCharge"]))
            {
                WSTaxClient client = new WSTaxClient();
                Tax tax = client.DetailTax(taxId, VariableConfigController.GetBucket());
                string[] arrIdStore = strIdStore.Split(',');
                string[] arrServiceCharge = strServiceCharge.Split(',');
                for (int i = 0; i < arrIdStore.Count(); i++)
                {
                    List<ServiceCharge> listServiceCharge = tax.arrServiceCharge;
                    var item = listServiceCharge.Where(r => r.index == int.Parse(arrIdStore[i])).First();
                    if (item != null)
                    {
                        string value = arrServiceCharge[i] != "" ? arrServiceCharge[i] : "0.00";
                        item.serviceChargeValue = double.Parse(value);
                    }
                }
                int response = client.WSCreateTax(tax, VariableConfigController.GetBucket());
                client.Close();
            }

            return RedirectToAction("Index");
        }

        public Boolean checkServiceChargeExist(string[] listIndex, string id)
        {
            WSTaxClient client = new WSTaxClient();
            Tax tax = client.DetailTax(id, VariableConfigController.GetBucket());
            if (tax.arrServiceCharge == null && tax.arrServiceCharge.Count == 0) return false;
            else
            {
                foreach (string index in listIndex)
                {
                    var serviceCharge = tax.arrServiceCharge.Where(s => s.store._id == index);
                    if (serviceCharge.Count() > 0) return true;
                }     
            }
            return false;
        }

        public ActionResult addNewTax(FormCollection collection)
        {
            ViewBag.Class = "tax";
            int type = int.Parse(collection["type"]);
            double value = double.Parse(collection["taxRate"]);
            string taxName = !string.IsNullOrEmpty(collection["taxName"])? collection["taxName"] : "";
            string strStoreId = collection["storeId"];
            string isTaxItemId = collection["submit"];
            string[] arrStoreId = null;
            if(!string.IsNullOrEmpty(strStoreId)){
                arrStoreId = strStoreId.Split(',');
            }
            string id = collection["taxId"];
            WSInventoryClient clientInventory = new WSInventoryClient();
            Inventory[] ListInventory = clientInventory.WSGetAll(ConstantSmoovs.CouchBase.DesigndocInventory, ConstantSmoovs.CouchBase.GetAllInventories, VariableConfigController.GetBucket());
            WSTaxClient client = new WSTaxClient();
            Tax tax = client.DetailTax(id, VariableConfigController.GetBucket());

            if (string.IsNullOrEmpty(isTaxItemId)) // add new servicecharge or Tax
            {
                //type == 1 : service charge
                if (type > 0)
                {
                    foreach (string idStore in arrStoreId)
                    {
                        ServiceCharge serviceCharge = new ServiceCharge();
                        serviceCharge.serviceChargeRate = Math.Round(value, 2, MidpointRounding.AwayFromZero);
                        serviceCharge.serviceChargeValue = Math.Round(value, 2, MidpointRounding.AwayFromZero);
                        var inventory = ListInventory.Where(i => i._id == idStore).FirstOrDefault();
                        serviceCharge.index = inventory.index;
                        serviceCharge.store = inventory;
                        if (tax.arrServiceCharge == null)
                        {
                            tax.arrServiceCharge = new List<ServiceCharge>();
                        }
                        tax.arrServiceCharge.Add(serviceCharge);
                    }


                }
                else // type == 0 : Tax item
                {
                    TaxItem taxItem = new TaxItem();
                    taxItem._id = Guid.NewGuid().ToString();
                    var idMerchant = VariableConfigController.GetIDMerchant();
                    taxItem.channels = new string[] { idMerchant+ "_pos" };
                    taxItem.display = true;
                    taxItem.isPercent = true;
                    taxItem.valueRate = Math.Round(value, 2);
                    taxItem.status = true;
                    taxItem.name = taxName;
                    taxItem.storeInformation = new List<StoreInformation>();
                    foreach (string idStore in arrStoreId)
                    {
                        var inventory = ListInventory.Where(i => i._id == idStore).FirstOrDefault();
                        StoreInformation storeInfo = new StoreInformation();
                        storeInfo.index = inventory.index;
                        storeInfo.storeID = inventory._id;
                        storeInfo.storeName = inventory.businessID;
                        storeInfo.valueRate = Math.Round(value, 2);
                        taxItem.storeInformation.Add(storeInfo);

                    }
                    if (tax.arrayTax == null)
                    {
                        tax.arrayTax = new List<TaxItem>();
                    }
                    tax.arrayTax.Add(taxItem);
                }
            }
            else // edit 
            {
                if (type > 0)
                {
                    var serviceCharge = tax.arrServiceCharge.Where(t => t.index == int.Parse(collection["isEdit"])).FirstOrDefault();
                    serviceCharge.serviceChargeRate = serviceCharge.serviceChargeValue = Math.Round(value, 2);
                }
                else
                {
                    var taxItem = tax.arrayTax.Where(t => t._id == isTaxItemId).FirstOrDefault();

Server/Cloud/SmoovPOS/merchant/Views/Tax/ListTaxItem.cshtml
@model Com.SmoovPOS.Entity.Tax
@*@{
  String urlImgDynamic = Url.Content("~/Content/Images/delete-ico.png");
}*@

<table class="table TaxesTable">       
    @if (Model.arrayTax != null)
    {
        foreach (var item in Model.arrayTax)
        {
            <tr>
                <td>
                    <button class="detailTax"  value="@Newtonsoft.Json.JsonConvert.SerializeObject(item)" data-toggle="modal" data-target="#detailTaxItemModal"><text>@item.name</text></button>                   
                </td>
                <td>
                    <text>@String.Format("{0:0.00}", item.valueRate) % </text> 
                </td>

                <td>                     
                    <button class="tnDeleteImage" onclick="deleteTax(this)" value="@Newtonsoft.Json.JsonConvert.SerializeObject(item)" id="btnDelete-@item._id" data-toggle="modal" data-target="#modalInactive"> <img src="@Url.Content("~/Content/Images/delete-ico.png")" width="15" height="15"></button>
                </td>
            </tr>
        }
    }

</table>

Server/Cloud/SmoovPOS/merchant/Views/Tax/NewTax.cshtml
@model SmoovPOS.UI.Models.Tax.TaxModel

<style>
    .add-tax > .col-md-6 {
        padding-left: 0px !important;
    }
</style>
@using (Html.BeginForm("addNewTax", "Tax", FormMethod.Post, new { @encType = "multipart/form-data" }))
{
    <div class="modal fade q-form" id="newTaxId" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    @* <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>*@
                    <h4 class="modal-title" id="myModalLabel">Add Tax</h4>
                </div>
                <input type="text" style="display:none" name="taxId" id="taxId" value="@Model.id">
                <input type="text" style="display:none" name="isEdit" id="isEdit" class="form-control" value="0">
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    @*<div class="validation-summary-errors">
                        <ul>
                            <li id="ErrTaxName" style="display:none">The Tax Name field is required.</li>
                            <li id="ErrTaxRate" style="display:none">The Tax Rate field is required.</li>
                            <li id="ErrStore" style="display:none">Please select at least 1 store.</li>
                            <li id="ErrServiceChargeExist" style="display:none">The Service Charge is exist</li>
                        </ul>
                    </div>*@
                    <div class="row">
                        <div class="add-tax col-md-12">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="type">Type</label>
                                    <select id="type" name="type" class="form-control" value="0">
                                        <option value="0">Tax</option>
                                        <option value="1">Service Charge</option>
                                    </select>
                                </div>
                                <span id="ErrServiceChargeExist" style="display:none" class="validation-summary-errors">The Service Charge is exist</span>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="value">Value</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="0.00" aria-describedby="basic-addon2" name="taxRate" id="taxRate" maxlength="6" value="0.00">
                                        <span class="input-group-addon" id="basic-addon2">%</span>
                                    </div>
                                </div>
                                <span id="ErrTaxRate" style="display:none" class="validation-summary-errors">The Tax Rate field is required.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 add-tax">
                            <div class="form-group">
                                <label for="name">Name</label><span style="color:red"> * </span>
                                <input type="text" class="form-control" maxlength="55" name="taxName" id="taxName">
                            </div>
                            <span id="ErrTaxName" style="display:none" class="validation-summary-errors">The Tax Name field is required.</span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <text>
                            Applied Store
                        </text><span style="color:red"> * </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class=" col-md-12 container">
                        <br>
                        @foreach (var item in Model.inventoryList)
                        {
                            <div id="@item._id"><input type="checkbox" class="storeId" name="storeId" value="@item._id" /> @item.businessID</div>
                            @*<br/>*@
                        }
                    </div>
                    <span id="ErrStore" style="display:none; padding-left:20px;" class="validation-summary-errors">Please select at least 1 store.</span>
                </div>
                <div class="modal-footer">
                    <div class="center loading" style="display:none">
                        <i class="fa fa-spinner fa-spin"></i>
                    </div>
                    <button type="button" class="btn btn-primary" id="btn-New-Tax">Add</button>
                    <button type="submit" class="btn btn-primary" id="submit" style="display:none" name="submit">Add</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
}